name: build
on: [push] 

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      # Make the documents
      - name: Build artefacts
        uses: docker://pandoc/core:2.9.1.1
        with: 
            args: -o pyconau-practicals.epub --toc --metadata-file metadata.yaml LICENCE.md README.md chapters/00_forward.md chapters/01_intro.md chapters/01_intro.md chapters/02_website.md chapters/03_sessions.md chapters/04_tickets.md chapters/05_lightning-talks.md chapters/06_financial_assistance.md chapters/07_shirts.md chapters/08-signage-and-customs.md chapters/09_sponsorship.md chapters/99_thanks.md

      # Saves a copy for checking and debugging
      - name: Save artefact
        uses: actions/upload-artifact@v1
        with:
          name: pyconau-practicals.epub
          path: pyconau-practicals.epub

      #
      # The following only runs on merge to master (either via a direct commit, or a merged pull request)
      #
      #

      - name: generate new tag name
        id: tag
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        run: ./bump.sh

      - name: Create Release
        id: create_release
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.new_tag }} 
          release_name: Release ${{ steps.tag.outputs.new_tag }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload_release_asset
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        uses: actions/upload-release-asset@v1.0.1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./pyconau-practicals.epub
          asset_name: pyconau-practicals.epub
          asset_content_type: application/epub+zip
