name: dump
on: [push]
env:
    MASTER_BRANCH: format("refs/heads/{}",github.event.repository.default_branch)

jobs:
  one:
    runs-on: ubuntu-16.04
    steps:
      - name: Run on push
        run: echo This runs on push
      - name: Run in merge try two
        if: endsWith(github.ref, github.event.repository.default_branch)
        run: echo This is the endsWith way
      - name: Run in merge try three
        if: github.ref == "refs/heads/master" #{{ github.event.repository.default_branch }}"
        run: echo This is the env ($MASTER_BRANCH)
