name: test
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: | 
          apt-get update
          apt-get install pandoc --no-dependencies
      - name: Build artefacts
        run: |
          pandoc *.md -o output.epub
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: true
      - name: Upload Release Asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: output.epub
          asset_name: output.epub
          asset_content_type: application/epub+zip
